### ISSUE TITLE
You remove my license

### ISSUE THREAD

**Issue by gravitano** [ps24love/shortcode#1]
I do not understand why you are so brave.

First, you download and change the namespace and the name of the vendor of the packages that I have made.

In ps24love/widget package, still listed the license that I created. However, the package ps24love/shortcode, you remove my license. This clearly violates the rules of github. https://help.github.com/articles/dmca-takedown-policy.

If indeed you have a surplus that could be implemented in my package, why not fork and make pull requests. I think, we can develop this package together.

I hope this could be your attention. I can send a ticket to support github if I want.

**Comment by ps24love** [comment]
i noticed that and am sorry about that, the reason i didnt fork the project was that i wanted to make huge changes to it which could change original idea and behaviour. this repo is here for personal experiment and i will take it down as soon as i finish, please bear with me
